# Generated by Django 3.0.8 on 2020-10-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='XXXX', max_length=4)),
                ('location', models.CharField(default='Phivolcs bldg, C.P. Garcia St., Diliman, Q.C', max_length=200)),
                ('repair_history', models.TextField()),
                ('transceiver_model', models.CharField(default='cygnus205', max_length=16)),
                ('stationname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapp.Station')),
            ],
        ),
    ]
