# Generated by Django 3.0.8 on 2020-10-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0002_remove_station_stationname'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(default='GFG', max_length=7)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('repair_date', models.DateField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stationapp.Station')),
            ],
        ),
    ]
