# Generated by Django 3.0.8 on 2020-10-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stationapp.Station'),
        ),
    ]
