# Generated by Django 3.0.8 on 2020-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0004_auto_20201004_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='personnel',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='repair_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
