# Generated by Django 3.0.8 on 2020-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0005_auto_20201004_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stationapp.Station'),
        ),
    ]
