# Generated by Django 3.0.8 on 2020-10-04 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0007_auto_20201004_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='personnel',
            field=models.CharField(default='GFG', max_length=7),
        ),
        migrations.AlterField(
            model_name='history',
            name='repair_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 4, 8, 6, 50, 913149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.CharField(default='enter text here', max_length=500),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(default='XXXX', max_length=4, null='False'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(default='Phivolcs bldg, C.P. Garcia St., Diliman, Q.C', max_length=200, null='False'),
        ),
        migrations.AlterField(
            model_name='station',
            name='transceiver_model',
            field=models.CharField(default='cygnus205', max_length=16, null='False'),
        ),
    ]
