# Generated by Django 3.0.8 on 2020-10-04 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0014_auto_20201004_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='save_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='repair_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
