# Generated by Django 3.0.8 on 2020-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0016_remove_history_save_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='save_history',
            field=models.BooleanField(default=False),
        ),
    ]
