# Generated by Django 3.0.8 on 2020-10-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0019_history_save_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stationapp.Station'),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(default='G.Ganipan', max_length=20)),
                ('observation', models.TextField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests', to='stationapp.Station')),
            ],
        ),
    ]
