# Generated by Django 3.0.8 on 2020-10-05 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0022_auto_20201005_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repair',
            old_name='personnel',
            new_name='repaired_by',
        ),
        migrations.AddField(
            model_name='repair',
            name='analysis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='repair',
            name='date_filed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='repair',
            name='operation_field',
            field=models.CharField(choices=[('OP', 'Operational'), ('NO', 'Not Operational')], default='MO', max_length=2),
        ),
        migrations.AddField(
            model_name='repair',
            name='problem_type_field',
            field=models.CharField(choices=[('WV', 'No Waveform Display'), ('DT', 'No Data Record'), ('NN', 'No Network Connection'), ('PS', 'Power Supply/Source'), ('SR', 'Sensor'), ('VZ', 'Vandalism'), ('SD', 'Structural Damage')], default='WV', max_length=2),
        ),
        migrations.AddField(
            model_name='repair',
            name='repair_procedure',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='repair',
            name='repair_type_field',
            field=models.CharField(choices=[('ST', 'DRC'), ('ST', 'Remote Access'), ('ST', 'On Site Visit'), ('ST', 'Phone Call/SMS')], default='MO', max_length=2),
        ),
        migrations.AddField(
            model_name='repair',
            name='report_type_field',
            field=models.CharField(choices=[('RQ', 'Request'), ('IN', 'Information')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='repair',
            name='reported_by',
            field=models.CharField(default='G.Ganipan', max_length=20),
        ),
        migrations.AlterField(
            model_name='repair',
            name='station_type_field',
            field=models.CharField(choices=[('ST', 'STSS'), ('SC', 'SCSS'), ('TA', 'Tsunami "TEWS" Alerting'), ('TD', 'Tsunami "TEWS" Detection'), ('TW', 'Tsunami "JICA" TWD'), ('DT', 'Tsunami "JICA" DTS'), ('IS', 'Intensity Meter SATREPS'), ('IJ', 'Intensity Meter JICA2'), ('SM', 'Strong Motion'), ('MO', 'Main Office')], default='MO', max_length=2),
        ),
    ]
