# Generated by Django 3.0.8 on 2020-10-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0024_remove_station_repair_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='transceiver_model',
        ),
        migrations.AddField(
            model_name='station',
            name='sensor_model',
            field=models.CharField(default='Trillium120', max_length=16, null='False'),
            preserve_default='False',
        ),
    ]
