# Generated by Django 3.0.8 on 2020-10-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapp', '0026_auto_20201008_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='digitizer_sn',
            field=models.CharField(default='0000', max_length=50, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='station',
            name='lnb_sn',
            field=models.CharField(default='0000', max_length=50, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='station',
            name='sensor_sn',
            field=models.CharField(default='0000', max_length=50, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='station',
            name='sspb_sn',
            field=models.CharField(default='0000', max_length=50, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='station',
            name='transceiver_model',
            field=models.CharField(default='Cygnus205', max_length=50, null='False'),
            preserve_default='False',
        ),
    ]
